# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import banking_pb2 as banking__pb2


class AccountServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/banking.AccountService/GetBalance',
                request_serializer=banking__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=banking__pb2.GetBalanceResponse.FromString,
                )
        self.UpdateBalance = channel.unary_unary(
                '/banking.AccountService/UpdateBalance',
                request_serializer=banking__pb2.UpdateBalanceRequest.SerializeToString,
                response_deserializer=banking__pb2.UpdateBalanceResponse.FromString,
                )


class AccountServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=banking__pb2.GetBalanceRequest.FromString,
                    response_serializer=banking__pb2.GetBalanceResponse.SerializeToString,
            ),
            'UpdateBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBalance,
                    request_deserializer=banking__pb2.UpdateBalanceRequest.FromString,
                    response_serializer=banking__pb2.UpdateBalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.AccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/banking.AccountService/GetBalance',
            banking__pb2.GetBalanceRequest.SerializeToString,
            banking__pb2.GetBalanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/banking.AccountService/UpdateBalance',
            banking__pb2.UpdateBalanceRequest.SerializeToString,
            banking__pb2.UpdateBalanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class TransactionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiateTransfer = channel.unary_unary(
                '/banking.TransactionService/InitiateTransfer',
                request_serializer=banking__pb2.InitiateTransferRequest.SerializeToString,
                response_deserializer=banking__pb2.InitiateTransferResponse.FromString,
                )
        self.GetTransactionHistory = channel.unary_unary(
                '/banking.TransactionService/GetTransactionHistory',
                request_serializer=banking__pb2.GetTransactionHistoryRequest.SerializeToString,
                response_deserializer=banking__pb2.GetTransactionHistoryResponse.FromString,
                )


class TransactionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitiateTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiateTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateTransfer,
                    request_deserializer=banking__pb2.InitiateTransferRequest.FromString,
                    response_serializer=banking__pb2.InitiateTransferResponse.SerializeToString,
            ),
            'GetTransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionHistory,
                    request_deserializer=banking__pb2.GetTransactionHistoryRequest.FromString,
                    response_serializer=banking__pb2.GetTransactionHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.TransactionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitiateTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/banking.TransactionService/InitiateTransfer',
            banking__pb2.InitiateTransferRequest.SerializeToString,
            banking__pb2.InitiateTransferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/banking.TransactionService/GetTransactionHistory',
            banking__pb2.GetTransactionHistoryRequest.SerializeToString,
            banking__pb2.GetTransactionHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
