# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banking.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbanking.proto\x12\x07\x62\x61nking\"$\n\x11GetBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"4\n\x12GetBalanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x01\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"<\n\x14UpdateBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0bnew_balance\x18\x02 \x01(\x01\"7\n\x15UpdateBalanceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"S\n\x17InitiateTransferRequest\x12\x14\n\x0c\x66rom_user_id\x18\x01 \x01(\t\x12\x12\n\nto_user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"R\n\x18InitiateTransferResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\"r\n\x0bTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_user_id\x18\x02 \x01(\t\x12\x12\n\nto_user_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"/\n\x1cGetTransactionHistoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"Z\n\x1dGetTransactionHistoryResponse\x12*\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x14.banking.Transaction\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xab\x01\n\x0e\x41\x63\x63ountService\x12G\n\nGetBalance\x12\x1a.banking.GetBalanceRequest\x1a\x1b.banking.GetBalanceResponse\"\x00\x12P\n\rUpdateBalance\x12\x1d.banking.UpdateBalanceRequest\x1a\x1e.banking.UpdateBalanceResponse\"\x00\x32\xd9\x01\n\x12TransactionService\x12Y\n\x10InitiateTransfer\x12 .banking.InitiateTransferRequest\x1a!.banking.InitiateTransferResponse\"\x00\x12h\n\x15GetTransactionHistory\x12%.banking.GetTransactionHistoryRequest\x1a&.banking.GetTransactionHistoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETBALANCEREQUEST']._serialized_start=26
  _globals['_GETBALANCEREQUEST']._serialized_end=62
  _globals['_GETBALANCERESPONSE']._serialized_start=64
  _globals['_GETBALANCERESPONSE']._serialized_end=116
  _globals['_UPDATEBALANCEREQUEST']._serialized_start=118
  _globals['_UPDATEBALANCEREQUEST']._serialized_end=178
  _globals['_UPDATEBALANCERESPONSE']._serialized_start=180
  _globals['_UPDATEBALANCERESPONSE']._serialized_end=235
  _globals['_INITIATETRANSFERREQUEST']._serialized_start=237
  _globals['_INITIATETRANSFERREQUEST']._serialized_end=320
  _globals['_INITIATETRANSFERRESPONSE']._serialized_start=322
  _globals['_INITIATETRANSFERRESPONSE']._serialized_end=404
  _globals['_TRANSACTION']._serialized_start=406
  _globals['_TRANSACTION']._serialized_end=520
  _globals['_GETTRANSACTIONHISTORYREQUEST']._serialized_start=522
  _globals['_GETTRANSACTIONHISTORYREQUEST']._serialized_end=569
  _globals['_GETTRANSACTIONHISTORYRESPONSE']._serialized_start=571
  _globals['_GETTRANSACTIONHISTORYRESPONSE']._serialized_end=661
  _globals['_ACCOUNTSERVICE']._serialized_start=664
  _globals['_ACCOUNTSERVICE']._serialized_end=835
  _globals['_TRANSACTIONSERVICE']._serialized_start=838
  _globals['_TRANSACTIONSERVICE']._serialized_end=1055
# @@protoc_insertion_point(module_scope)
